import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { HeaderComponent, FooterComponent, ContainerComponent } from '../components';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'My Next.js Blog',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${inter.className} bg-zinc-100 text-zinc-900 min-h-screen`}>
                <ContainerComponent>
                    <HeaderComponent />
                    {children}
                    <FooterComponent />
                </ContainerComponent>
            </body>
        </html>
    );
}
